# blacklisted words: not tickers but common language in wsb
blacklist = {'PDFUA', 'ELON', 'FBI', 'DEC', 'IT', 'OP', 'AT', 'GDP', 'DR', 'U', 'GG', 'SEP', 'IL',
             'FIFA', 'AYYMD', 'RISE', 'LMFAO', 'EOD', 'RH', 'FOMO', 'USA', 'RIP', 'ON', 'ER', 'CFO',
             'RAW', 'SO', 'OR', 'RED', 'LPT', 'NOV', 'AUG', 'ICE', 'ITM', 'BEZOS', 'ATH', 'PC',
             'IPO', 'BTFD', 'POS', 'BE', 'EZ', 'HQ', 'FL', 'YOLO', 'TL;DR', 'BIG', 'DJIA', 'SEPT',
             'OCT', 'GOAT', 'ISIS', 'MAR', 'BUT', 'TYS', 'IPA', 'A', 'TL', 'PDT', 'CAN', 'OPEN',
             'LGMA', 'AM', 'ATM', 'PT', 'AH', 'FEB', 'CA', 'EDIT', 'UK', 'DOJ', 'GO', 'DOW', 'JAN',
             'OUT', 'NOT', 'CTO', 'WTF', 'FOR', 'STAY', 'USD', 'EV', 'RIDE', 'IMO', 'STILL', 'ARE',
             'JUL', 'GOOD', 'PM', 'IV', 'CPU', 'URL', 'SSN', 'SEC', 'IS', 'IRS', 'TOS', 'PS', 'COD',
             'NOW', 'KYS', 'ONE', 'SEE', 'PRAY', 'OTM', 'ALL', 'FD', 'ROPE', 'I', 'GOD', 'BMW',
             'CEO', 'WSB', 'BY', 'FDA', 'PR', 'OK', 'MILF', 'LOVE', 'LOL', 'TICK', 'LMAO', 'THE',
             'HAS', 'US', 'DD', 'ROFL', 'MACD', 'ETF', 'DC', 'RH', 'CRY', 'G', 'BILL', 'INFO', 'AI',
             'H', 'HODL', 'GEM', 'NYC', 'IP'
             }

# adding wsb/reddit flavour to vader to improve sentiment analysis, score: 4.0 to -4.0
# *modifying list from https://github.com/asad70/reddit-sentiment-analysis/blob/master
wsb_words = {
    'citron': -4.0,
    'hidenburg': -4.0,
    'moon': 4.0,
    'highs': 2.0,
    'mooning': 4.0,
    'long': 2.0,
    'short': -2.0,
    'shorting': -3.0,
    'shorted': -2.5,
    'call': 4.0,
    'calls': 4.0,
    'put': -4.0,
    'puts': -4.0,
    'break': 2.0,
    'tendie': 2.0,
    'tendies': 2.0,
    'town': 2.0,
    'overvalued': -3.0,
    'undervalued': 3.0,
    'buy': 4.0,
    'sell': -4.0,
    'gone': -1.0,
    'gtfo': -1.7,
    'paper': -1.7,
    'bullish': 3.7,
    'bearish': -3.7,
    'bagholder': -1.7,
    'stonk': 1.9,
    'green': 1.9,
    'money': 1.2,
    'print': 2.2,
    'rocket': 2.2,
    'bull': 2.9,
    'bear': -2.9,
    'pumping': -1.0,
    'sus': -3.0,
    'offering': -2.3,
    'rip': -4.0,
    'downgrade': -3.0,
    'upgrade': 3.0,
    'maintain': 1.0,
    'pump': 1.9,
    'hot': 1.5,
    'drop': -2.5,
    'rebound': 1.5,
    'crack': 2.5,
    'faggot': -1.5,
    'rope': -3.5,
    'dump': -1.9,
    'dumping': 1.0,
    'hype': 3.0,
    'retard': 1.0,
    'moron': 0.5,
    'fire': 2.5,
    'hodl': 3,

}

# emoji sentiment dictionary, completely empirical, would be nice to tune these with neutral network
# if I knew how
emojis = {
    '🚀': 2.5,   # 🚀
    '🌙': 2.5,   # 🌙
    '💎': 2.0,   # 💎
    '💪': 0.8,
    '🐂': 0.5,
    '🐻': -0.5,
    '🧻': -1.5,
    '💵': 2.0,
    '✅': 1.5,
    '❌': -1.5,
    '☀️': 3,
    '📈': 3,
    '📉': -3,
    '💰': 1.5
}

common = {
    "about", "above", "across", "after",
    "against", "among", "around", "at",
    "before", "behind", "below", "beside",
    "between", "by", "down", "during",
    "for", "from", "in", "inside",
    "into", "near", "of", "off",
    "on", "out", "over", "through",
    "to", "toward", "under", "up",
    "with", 'he', 'she', 'him', 'her', 'it', 'the',
    'and', 'share', 'shares', 'stock', 'stocks', 'common',
    "alaska", "alabama", "arkansas", "arizona", "california", "colorado",
    "connecticut", "delaware", "florida", "georgia", "guam", "hawaii",
    "iowa", "idaho", "illinois", "indiana", "kansas", "kentucky", "louisiana", "massachusetts",
    "maryland", "maine", "michigan", "minnesota", "missouri", "mississippi", "montana",
    "north carolina", "north dakota", "nebraska", "new", "hampshire", "jersey", "mexico",
    "nevada", "york", "ohio", "oklahoma", "oregon", "pennsylvania",
    "rhode", "island", "south", "carolina", "dakota", "tennessee", "texas", "utah", "virginia",
    "vermont", "washington", "wisconsin", "east", "west", "virginia", "wyoming", "no",
    'call', 'house', 'medical', 'german', 'american', 'china', 'chinese', 'wireless',
    'communication', 'dana', 'data', 'treasury', 'bond', 'interest', 'good', 'bank', 'nasdaq',
    'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven',
    'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen',
    'twenty', 'white', 'black', 'yellow', 'red', 'federal', 'powell', 'all', 'you', 'holdings',
    'is', 'are', 'buy', 'cry', 'cycle', 'news', 'new', 'diamond', 'first', 'silver', 'brand',
    'energy', 'acquisition', 'holding', 'perfect', 'world', 'units', 'super', 'micro', 'computer',
    'real', 'company', 'companies', 'well', 'national', 'retail', 'properties'
    'alpha', 'sigma', 'resource', 'resources', 'beta', 'corporation', 'ocean', 'portfolio', 'full',
    'mining', 'male', 'female', 'group', 'cloud', 'blockchain', 'data', 'office', 'storage', 'big',
    'vision', 'right', 'almost', 'live', 'factory', 'price', 'cost', 'pharma', 'line', 'holdings',
    'ultimate', 'software', 'hardware', 'cruise', 'cannabis', 'top', 'image', 'system', 'systems',
    'canada'
}
